docsPath: 'api-docs'
useAuthentication: false

info:
  title: MOCA Codex API Documentation
  version: 1.0.0

tags:
  - name: Codex
  - name: Files

publishedTags:
  - Codex
  - Files

paths:
  "/items/codex":
    get:
      summary: List Codex Items
      tags:
        - Codex
      parameters:
        - $ref: '#/components/parameters/Fields'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Meta'
        - $ref: '#/components/parameters/Offset'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Filter'
        - $ref: '#/components/parameters/Search'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ItemsCodex'
                  meta:
                    $ref: '#/components/schemas/x-metadata'

  "/items/codex/{id}":
    get:
      summary: Get Codex Item by ID
      tags:
        - Codex
      parameters:
        - $ref: '#/components/parameters/Fields'
        - $ref: '#/components/parameters/Meta'
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/ItemsCodex'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: integer
                        format: int64
                      message:
                        type: string

  "/items/codex?filter[owner][_eq]=0x614a61a3b7f2fd8750acaad63b2a0cfe8b8524f1":
    get:
      summary: Query Codex Items by Owner
      tags:
        - Codex
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ItemsCodex'
                  meta:
                    $ref: '#/components/schemas/x-metadata'

  "/files":
    get:
      summary: List Files
      tags:
        - Files
      parameters:
        - $ref: '#/components/parameters/Fields'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Meta'
        - $ref: '#/components/parameters/Offset'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Filter'
        - $ref: '#/components/parameters/Search'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Files'
                  meta:
                    $ref: '#/components/schemas/x-metadata'

  "/files/{id}":
    get:
      summary: Get File by ID
      tags:
        - Files
      parameters:
        - $ref: '#/components/parameters/Fields'
        - $ref: '#/components/parameters/Meta'
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Files'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: integer
                        format: int64
                      message:
                        type: string

  "/assets/{id}":
    get:
      summary: Get Asset
      tags:
        - Files
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: width
          in: query
          schema:
            type: integer
        - name: height
          in: query
          schema:
            type: integer
        - name: quality
          in: query
          schema:
            type: integer
        - name: fit
          in: query
          schema:
            type: string
            enum: [cover, contain, inside, outside]
        - name: format
          in: query
          schema:
            type: string
            enum: [jpeg, png, webp, tiff, avif]
        - name: key
          in: query
          schema:
            type: string
        - name: transforms
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                type: string
                format: binary
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: integer
                        format: int64
                      message:
                        type: string